### ISSUE TITLE
Add Spring Boot Support Matrix

### ISSUE THREAD

**Issue by stonio** [wiremock/wiremock-spring-boot#98]
### Summary

Can you document which **Spring Boot** versions are supported by **Wiremock Spring Boot**?
A support matrix could be an option.

Related to #81.

### References

My project is based on  **Spring Boot** 3.3.11 (Java 17 ;  Spring WebFlux) and works well with **Wiremock Spring Boot** 3.7.0. 

However I have an error with **Wiremock Spring Boot** 3.8.0 or newer:

```log
Caused by: java.lang.NoSuchMethodError: 'org.apache.hc.client5.http.config.RequestConfig$Builder org.apache.hc.client5.http.config.RequestConfig$Builder.setProtocolUpgradeEnabled(boolean)'
``

**Comment by tomasbjerre** [comment]
You will find the Spring Boot version used for testing in the [build.gradle](https://github.com/wiremock/wiremock-spring-boot/blob/main/build.gradle). And if you want to know which one was used for a specific version I would suggest view that revision, that tag, of the build.gradle.

In next major-version (#96) I think I'd like to make all the Spring-dependencies `compileOnly` so that the user can easily pick the versions to use.

**Comment by gyula-lakatos-bw** [comment]
Unfortunately, that file only goes back till the tag 'v2.2.0' and even then it points to SB version 'org.springframework.boot:spring-boot-starter-test:3.3.4'. :/

**Comment by tomasbjerre** [comment]
The work effort needed to maintain such a matrix is the problem here. My strategy is basically to support the latest of all versions, it requires minimal work effort for me.

**Comment by wimdeblauwe-volvo** [comment]
I don't think maintaining this matrix manually is that big of a work. I do it for my libraries as well. You can see a sample at [error-handling-spring-boot-starter](https://github.com/wimdeblauwe/error-handling-spring-boot-starter?tab=readme-ov-file#spring-boot-compatibility) or [spring-boot-htmx](https://github.com/wimdeblauwe/htmx-spring-boot?tab=readme-ov-file#spring-boot-compatibility) if you are curious how I do it.

**Comment by tomasbjerre** [comment]
If you want to maintain such a matrix here in the readme, that is fine by me. Just make sure you watch for new releases and update it when needed.

**Comment by tomasbjerre** [comment]
There is a standalone alternative now that probably gets rid of the original classpath issue.
